import React, { useMemo, useState } from "react";
import { Eye, Merge, RotateCcw, Search, X } from "lucide-react";
import { BORDER, F, MUTED, RED, TEXT } from "./shared";

const TINH_TRANG = ["Đã có kết quả giải quyết", "Đã có kết quả giải quyết và còn đơn thụ lý mới", "Chưa có kết quả giải quyết", "Chưa chuyển đơn", "Đã có kết quả giải quyết và còn đơn chưa chuyển", "Đã có kết quả giải quyết và chưa có kết quả xét xử"];

type AggregateRow = {
  id:number; ma:string; ten:string; ngayTao:string; tam:string[]; qh:boolean; soDon:number; trangThai:"Đang giải quyết"|"Đã giải quyết"; tinhTrang:string;
  stages:{giaiDoan:string; so:string; ngay:string; toa:string}[];
};

const DATA: AggregateRow[] = [
  {id:1,ma:"HS26-000021",ten:"Giết người – Nguyễn Văn An",ngayTao:"18/08/2026",tam:["HS26-000145T","HS26-000188T"],qh:true,soDon:4,trangThai:"Đang giải quyết",tinhTrang:TINH_TRANG[5],stages:[{giaiDoan:"Sơ thẩm",so:"244/2025/HS-ST",ngay:"23/12/2025",toa:"TAND TP Hải Phòng"},{giaiDoan:"Phúc thẩm",so:"51/2026/HS-PT",ngay:"12/03/2026",toa:"TAND cấp cao tại Hà Nội"},{giaiDoan:"GĐT",so:"28/2026/KN-HS",ngay:"07/04/2026",toa:"TANDTC"}]},
  {id:2,ma:"HS26-000037",ten:"Tranh chấp QSDĐ – Nguyễn Văn Minh và Trần Thị Lan",ngayTao:"22/08/2026",tam:["HS26-000201T"],qh:false,soDon:3,trangThai:"Đang giải quyết",tinhTrang:TINH_TRANG[1],stages:[{giaiDoan:"Sơ thẩm",so:"18/2024/DS-ST",ngay:"18/09/2024",toa:"TAND tỉnh An Giang"},{giaiDoan:"Phúc thẩm",so:"74/2025/DS-PT",ngay:"10/04/2025",toa:"TAND cấp cao tại TP.HCM"}]},
  {id:3,ma:"HS26-000042",ten:"Khiếu kiện quyết định hành chính – Lê Thị Hoa",ngayTao:"25/08/2026",tam:[],qh:false,soDon:2,trangThai:"Đã giải quyết",tinhTrang:TINH_TRANG[0],stages:[{giaiDoan:"Sơ thẩm",so:"12/2025/HC-ST",ngay:"16/11/2025",toa:"TAND tỉnh Điện Biên"},{giaiDoan:"Phúc thẩm",so:"08/2026/HC-PT",ngay:"20/02/2026",toa:"TAND cấp cao tại Hà Nội"}]},
];

const lbl: React.CSSProperties={display:"block",fontSize:10.5,color:MUTED,marginBottom:4};
const inp: React.CSSProperties={width:"100%",boxSizing:"border-box",padding:"7px 8px",border:`1px solid ${BORDER}`,borderRadius:4,fontSize:11,fontFamily:F};
const th: React.CSSProperties={padding:"8px",border:`1px solid ${BORDER}`,fontSize:10.5,textAlign:"left",background:"#f8fafc",whiteSpace:"nowrap"};
const td: React.CSSProperties={padding:"8px",border:`1px solid ${BORDER}`,fontSize:11,verticalAlign:"top"};

function Detail({row,onBack,onIntegrate}:{row:AggregateRow;onBack:()=>void;onIntegrate:()=>void}){
  const [showDon,setShowDon]=useState(true); const [showST,setShowST]=useState(false); const [showPT,setShowPT]=useState(true); const [showGDT,setShowGDT]=useState(true);
  const dons=[
    ["1","Nguyễn Văn A","Đơn đề nghị GĐT – 09/07/2026","D-26070901","Đã chuyển Vụ GĐ,KT","Đã thụ lý"],
    ["2","Trần Thị B","Công văn kiến nghị – 15/07/2026","D-26071512","Đã có KQGQ","Đã thụ lý"],
    ["3","Công ty X","Đơn bổ sung – 20/08/2026","D-26082003","Chờ chuyển Vụ","Thụ lý mới"],
  ];
  return <div style={{padding:20,fontFamily:F,height:"100%",overflow:"auto",background:"#f8fafc"}}>
    <div style={{fontSize:11,color:MUTED,marginBottom:8}}>Trang chủ › Hồ sơ tổng hợp vụ án › Chi tiết</div>
    <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><button onClick={onBack} style={{...inp,width:"auto",cursor:"pointer",background:"#fff"}}>← Quay lại</button><h2 style={{margin:0,fontSize:19,color:TEXT}}>Chi tiết hồ sơ tổng hợp {row.ma}</h2></div>
    <section style={{background:"#fff",border:`1px solid ${BORDER}`,borderRadius:8,padding:14,marginBottom:12}}><b>Vụ án gốc</b><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginTop:10,fontSize:11}}><div><span style={lbl}>Mã hồ sơ tổng hợp</span><b>{row.ma}</b></div><div><span style={lbl}>Tên vụ án</span>{row.ten}</div><div><span style={lbl}>Ngày tạo</span>{row.ngayTao}</div><div><span style={lbl}>Trạng thái</span>{row.trangThai}</div><div style={{gridColumn:"span 2"}}><span style={lbl}>Tình trạng</span>{row.tinhTrang}</div></div></section>
    <section style={{background:"#fff",border:`1px solid ${BORDER}`,borderRadius:8,padding:14,marginBottom:12}}><div style={{display:"flex",gap:14,alignItems:"center",marginBottom:10}}><b>Thông tin bản án</b><label><input type="checkbox" checked={showST} onChange={e=>setShowST(e.target.checked)}/> Sơ thẩm</label><label><input type="checkbox" checked={showPT} onChange={e=>setShowPT(e.target.checked)}/> Phúc thẩm</label><label><input type="checkbox" checked={showGDT} onChange={e=>setShowGDT(e.target.checked)}/> GĐT/TT</label></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8}}>{row.stages.filter(s=>(s.giaiDoan==="Sơ thẩm"?showST:s.giaiDoan==="Phúc thẩm"?showPT:showGDT)).map(s=><div key={s.giaiDoan+s.so} style={{border:`1px solid ${BORDER}`,padding:10,borderRadius:6,fontSize:11}}><b>{s.giaiDoan}</b><div>Số: {s.so}</div><div>Ngày: {s.ngay}</div><div>Tòa: {s.toa}</div></div>)}</div></section>
    <section style={{background:"#fff",border:`1px solid ${BORDER}`,borderRadius:8,padding:14,marginBottom:12}}><label style={{fontWeight:700}}><input type="checkbox" checked={showDon} onChange={e=>setShowDon(e.target.checked)}/> Danh sách đơn</label>{showDon&&<table style={{width:"100%",borderCollapse:"collapse",marginTop:10}}><thead><tr>{["STT","Người/đơn vị đứng đơn","Thông tin đơn","Số đơn","Thông tin giải quyết","Kết quả thụ lý",""].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{dons.slice(0,row.soDon).map(d=><tr key={d[0]}>{d.map((v,i)=><td key={i} style={td}>{v}</td>)}<td style={td}><Eye size={14}/></td></tr>)}</tbody></table>}</section>
    <section style={{background:"#fff",border:`1px solid ${BORDER}`,borderRadius:8,padding:14}}><div style={{display:"flex",alignItems:"center",gap:8}}><b>Vụ án tạm</b><span style={{flex:1}}/><button disabled={!row.tam.length} onClick={onIntegrate} style={{padding:"6px 12px",border:0,borderRadius:4,background:row.tam.length?RED:"#d1d5db",color:"#fff",cursor:row.tam.length?"pointer":"not-allowed",fontFamily:F}}><Merge size={13} style={{verticalAlign:"middle"}}/> Tích hợp vụ án tạm</button></div>{row.tam.length?<div style={{display:"flex",gap:8,marginTop:10}}>{row.tam.map(t=><span key={t} style={{padding:"5px 9px",border:`1px solid ${BORDER}`,borderRadius:4,color:"#2563eb",fontSize:11}}>{t}</span>)}</div>:<div style={{color:MUTED,fontSize:11,marginTop:8}}>Không có vụ án tạm gợi ý.</div>}</section>
  </div>
}

export default function HoSoTongHopVuAnView(){
  const [filters,setFilters]=useState({toa:"",so:"",ngay:"",loai:"",thuoc:"",nhanTu:"",nhanDen:"",thuLyTu:"",thuLyDen:"",ma:"",thoiHieu:""});
  const [selected,setSelected]=useState<number[]>([]); const [detail,setDetail]=useState<AggregateRow|null>(null); const [confirm,setConfirm]=useState(false); const [queryTick,setQueryTick]=useState(0);
  const change=(k:string,v:string)=>setFilters(p=>({...p,[k]:v}));
  const result=useMemo(()=>DATA.filter(r=>!filters.ma||r.ma.toLowerCase().includes(filters.ma.toLowerCase())).filter(r=>!filters.so||r.stages.some(s=>s.so.toLowerCase().includes(filters.so.toLowerCase()))),[filters.ma,filters.so,queryTick]);
  const search=()=>{if(filters.nhanTu&&filters.nhanDen&&filters.nhanTu>filters.nhanDen){alert("Từ ngày không được lớn hơn Đến ngày");return;} if(filters.thuLyTu&&filters.thuLyDen&&filters.thuLyTu>filters.thuLyDen){alert("Từ ngày không được lớn hơn Đến ngày");return;}setQueryTick(x=>x+1)};
  const integrate=()=>{if(!selected.length){alert("Chọn hồ sơ có vụ án tạm để tích hợp");return;}setConfirm(true)};
  if(detail)return <Detail row={detail} onBack={()=>setDetail(null)} onIntegrate={()=>{setSelected([detail.id]);setConfirm(true)}}/>;
  return <div style={{padding:20,fontFamily:F,height:"100%",overflow:"auto",background:"#f8fafc"}}>
    <div style={{fontSize:11,color:MUTED,marginBottom:8}}>Trang chủ › Quản lý án GĐT/TT › Hồ sơ tổng hợp vụ án</div><h2 style={{margin:"0 0 12px",fontSize:19,color:TEXT}}>Danh sách hồ sơ tổng hợp vụ án</h2>
    <div style={{background:"#fff",border:`1px solid ${BORDER}`,borderRadius:8,padding:14,marginBottom:12}}><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10}}>
      {[['Tòa ra BA/QĐ','toa','select'],['Số BA/QĐ','so','text'],['Ngày BA/QĐ','ngay','date'],['Loại án','loai','select'],['Thuộc án','thuoc','select'],['Nhận đơn từ ngày','nhanTu','date'],['Nhận đơn đến ngày','nhanDen','date'],['Thụ lý từ ngày','thuLyTu','date'],['Thụ lý đến ngày','thuLyDen','date'],['Mã số vụ án tổng hợp','ma','text'],['Án thời hiệu','thoiHieu','select']].map(([l,k,t])=><div key={k}><label style={lbl}>{l}</label>{t==='select'?<select value={(filters as any)[k]} onChange={e=>change(k,e.target.value)} style={inp}><option value="">– Tất cả –</option>{k==='loai'&&['Hình sự','Dân sự','KDTM','Hành chính'].map(x=><option key={x}>{x}</option>)}{k==='thuoc'&&['Án Quốc Hội','Án chỉ đạo','Án tử hình'].map(x=><option key={x}>{x}</option>)}{k==='thoiHieu'&&['< 3 tháng','> 3 tháng','Quá hạn'].map(x=><option key={x}>{x}</option>)}</select>:<input type={t} value={(filters as any)[k]} onChange={e=>change(k,e.target.value)} style={inp}/>}</div>)}
    </div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:12}}><button onClick={()=>{setFilters({toa:"",so:"",ngay:"",loai:"",thuoc:"",nhanTu:"",nhanDen:"",thuLyTu:"",thuLyDen:"",ma:"",thoiHieu:""});setQueryTick(x=>x+1)}} style={{padding:"7px 13px",border:`1px solid ${BORDER}`,background:"#fff",borderRadius:4,fontFamily:F,cursor:"pointer"}}><RotateCcw size={13}/> Làm mới</button><button onClick={search} style={{padding:"7px 14px",border:0,background:RED,color:"#fff",borderRadius:4,fontFamily:F,cursor:"pointer"}}><Search size={13}/> Tìm kiếm</button></div></div>
    <div style={{display:"flex",alignItems:"center",marginBottom:8}}><button onClick={integrate} style={{padding:"7px 12px",border:0,background:RED,color:"#fff",borderRadius:4,fontFamily:F,cursor:"pointer"}}><Merge size={13}/> Tích hợp vụ án tạm{selected.length?` (${selected.length})`:''}</button><span style={{flex:1}}/><span style={{fontSize:11,color:MUTED}}>Sắp xếp: đơn xử lý gần nhất → xa nhất</span></div>
    <div style={{background:"#fff",border:`1px solid ${BORDER}`,borderRadius:8,overflowX:"auto"}}><table style={{width:"100%",minWidth:1100,borderCollapse:"collapse"}}><thead><tr>{["","STT","Thông tin vụ án tổng hợp","Thông tin vụ án","Án QH","Số đơn","Trạng thái","Tình trạng","Thao tác"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{result.length===0?<tr><td colSpan={9} style={{...td,textAlign:'center',color:MUTED,padding:28}}>Không có dữ liệu phù hợp với điều kiện tìm kiếm.</td></tr>:result.map((r,i)=><tr key={r.id}><td style={td}><input type="checkbox" disabled={!r.tam.length} checked={selected.includes(r.id)} onChange={e=>setSelected(p=>e.target.checked?[...p,r.id]:p.filter(x=>x!==r.id))}/></td><td style={td}>{i+1}</td><td style={td}><b style={{color:'#2563eb'}}>{r.ma}</b><div>{r.ten}</div><div style={{fontSize:10,color:MUTED}}>Ngày tạo: {r.ngayTao}</div>{r.tam.map(t=><div key={t} style={{color:'#2563eb',fontSize:10}}>Vụ án tạm: {t}</div>)}</td><td style={td}>{r.stages.map(s=><div key={s.giaiDoan+s.so} style={{marginBottom:5}}><b>{s.giaiDoan}</b>: {s.so} – {s.ngay}<div style={{fontSize:10,color:MUTED}}>{s.toa}</div></div>)}</td><td style={{...td,textAlign:'center'}}>{r.qh?'🏛️':''}</td><td style={{...td,textAlign:'center'}}>{r.soDon}</td><td style={td}><span style={{padding:'3px 7px',borderRadius:20,background:r.trangThai==='Đã giải quyết'?'#dcfce7':'#fef3c7',color:r.trangThai==='Đã giải quyết'?'#166534':'#92400e'}}>{r.trangThai}</span></td><td style={td}>{r.tinhTrang}</td><td style={{...td,textAlign:'center'}}><button onClick={()=>setDetail(r)} title="Xem chi tiết" style={{border:0,background:'transparent',cursor:'pointer'}}><Eye size={15}/></button></td></tr>)}</tbody></table></div>
    <div style={{display:'flex',alignItems:'center',marginTop:8,fontSize:11,color:MUTED}}><span>Hiển thị 1-{result.length} trong tổng số {result.length} vụ án</span><span style={{flex:1}}/><button style={{...inp,width:'auto',background:'#fff'}}>Trước</button><button style={{...inp,width:'auto',background:'#fff',marginLeft:4}}>1</button><button style={{...inp,width:'auto',background:'#fff',marginLeft:4}}>Sau</button></div>
    {confirm&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.4)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:2000}}><div style={{width:480,background:'#fff',borderRadius:8,boxShadow:'0 15px 40px rgba(0,0,0,.2)',fontFamily:F}}><div style={{display:'flex',padding:14,borderBottom:`1px solid ${BORDER}`,alignItems:'center'}}><b style={{flex:1}}>Xác nhận tích hợp vụ án tạm</b><button onClick={()=>setConfirm(false)} style={{border:0,background:'transparent'}}><X size={16}/></button></div><div style={{padding:18,fontSize:12,lineHeight:1.6}}>Bạn có chắc chắn muốn tích hợp các <b>Hồ sơ vụ án tạm</b> vào <b>Hồ sơ tổng hợp vụ án</b>? Bản ghi vụ án tạm sẽ được xóa mềm sau khi tích hợp.</div><div style={{display:'flex',justifyContent:'flex-end',gap:8,padding:14,borderTop:`1px solid ${BORDER}`}}><button onClick={()=>setConfirm(false)} style={{padding:'7px 14px',background:'#fff',border:`1px solid ${BORDER}`,borderRadius:4}}>Đóng</button><button onClick={()=>{setConfirm(false);setSelected([]);alert('Tích hợp vụ án tạm thành công (mockup).')}} style={{padding:'7px 14px',background:RED,color:'#fff',border:0,borderRadius:4}}>Xác nhận</button></div></div></div>}
    <div style={{fontSize:10,color:MUTED,marginTop:10}}>Đối chiếu SRS: mã hồ sơ tổng hợp dùng HS[YY]-XXXXXX và mã vụ án tạm HS[YY]-XXXXXXT. Quy tắc tự động ghép BR-01/BR-03/BR-04/BR-05 được biểu diễn ở trạng thái mockup; xử lý DB/xóa mềm thực tế thuộc backend.</div>
  </div>;
}
